import {hullConfig,sailConfig,FIGUREHEADS,FLAGS,SHIP_TUNING,figureBonus} from './ship-config.js';
import {SAIL_STYLES} from './ship-art-layout.js';
import {ECON} from './catalog.js';

export function inventory(s,category,{button,cost}){
 const items=category==='sails'?SAIL_STYLES.map(([asset,name],id)=>({id,name,image:'sails/'+asset+'.png',owned:s.cosmetics.includes(id),equipped:s.cosmetic===id,cost:{gold:ECON.SAILS[id]},action:'cosmetic',label:'Sail appearance'})):
 category==='flags'?FLAGS.map(f=>({...f,owned:s.flags.includes(f.id),equipped:s.flag===f.id,action:'flag',label:'Flag appearance'})):
 FIGUREHEADS.map(f=>({...f,image:f.asset,owned:!!s.figureheads[f.id],equipped:s.figurehead===f.id,cost:{gold:f.gold,gems:f.gems},action:'figure',grade:s.figureheads[f.id]||0,label:`+${Math.round(figureBonus({figure:f.id,figureGrade:s.figureheads[f.id]||1},f.bonusType)*1000)/10}% ${f.label.toLowerCase()}`}));
 return items.sort((a,b)=>Number(b.owned)-Number(a.owned)).map(f=>`<article class="equipment-card ${f.equipped?'equipped':''}">${f.image?`<img src="./public/ship-art/${f.image}" alt="${f.name}">`:'<div class="asset-pending">Artwork pending</div>'}<h3>${f.name}</h3><span class="equipment-label">${f.equipped?'EQUIPPED':f.owned?'OWNED':'AVAILABLE'}</span><small>${f.label}</small>${button(f.equipped?'Equipped ✓':f.owned?'Equip':cost(f.cost),f.action,f.id,'small',f.equipped)}${f.grade&&f.grade<4?button('Improve · '+cost({gold:ECON.FIG_UPGRADE.gold[f.grade-1],gems:ECON.FIG_UPGRADE.gems[f.grade-1]}),'figure-up',f.id,'small'):''}</article>`).join('');
}
export function shipScreen(s,category,helpers){
 const {button,cost,diagram,materials}=helpers,h=hullConfig(s.shipLevel),rig=sailConfig(s.sailLevel),inBattle=!!s.battle&&s.battle.phase!=='result';
 return `<div class="ship-customization"><section class="card ship-focus"><div class="row between"><div><span class="eyebrow">YOUR SHIP</span><h2>The Blackwake</h2></div><span class="pill">HULL ${h.level} / 6</span></div>${diagram()}<div class="upgrade-status" aria-live="polite"></div>
 <div class="ship-summary"><div><strong>${h.hp}</strong><small>HULL HP</small></div><div><strong>${h.deck} + ${h.hold}</strong><small>GUNNER SLOTS</small></div><div><strong>${rig.masts.length} / ${rig.panels.length}</strong><small>MASTS / SAILS</small></div></div>${materials()}
 <div class="ship-controls">${button(h.cost?'Upgrade Hull':'Hull complete','ship-up',h.level,'primary',!h.cost||inBattle)}${button(rig.cost?'Upgrade Sails':'Sails complete','sail-up',s.sailLevel,'',!rig.cost||inBattle)}<small>${h.cost?cost(h.cost):'All 8 gunner slots unlocked'}</small><small>${rig.cost?cost(rig.cost):'Future: front jib and rear spanker'}</small></div>
 <div class="custom-shortcuts">${[['sails','Customize Sails'],['flags','Customize Flag'],['figureheads','Customize Figurehead']].map(([key,label])=>button(label,'inventory-tab',key,'ghost')).join('')}</div>${inBattle?'<p class="footer-note">Finish your current battle before upgrading.</p>':''}</section>
 <aside class="card ship-inventory"><h3>Your collection</h3><div class="inventory-tabs" role="tablist" aria-label="Ship customization">${[['sails','Sails'],['flags','Flags'],['figureheads','Figureheads']].map(([key,label])=>`<button role="tab" aria-selected="${category===key}" aria-controls="shipInventory" data-action="inventory-tab" data-id="${key}">${label}</button>`).join('')}</div><div id="shipInventory" class="inventory-scroll" role="tabpanel" aria-label="${category} inventory" tabindex="0">${inventory(s,category,helpers)}</div></aside></div>`;
}
export function upgradeComparison(before,after){return `<div class="eyebrow">SHIP UPGRADED</div><h2>Hull Level ${after.level}</h2><p>One more gunner. A stronger ship.</p><table class="upgrade-comparison"><thead><tr><th>Improvement</th><th>Before</th><th>Now</th></tr></thead><tbody><tr><th>Hull HP</th><td>${before.hp}</td><td>${after.hp}</td></tr><tr><th>Movement per action</th><td>${(SHIP_TUNING.baseMove*10*before.movement).toFixed(2)} m</td><td>${(SHIP_TUNING.baseMove*10*after.movement).toFixed(2)} m</td></tr><tr><th>Gunner capacity</th><td>${before.capacity}</td><td>${after.capacity}</td></tr><tr><th>Cannon ports</th><td>${before.ports}</td><td>${after.ports}</td></tr></tbody></table><button class="primary" data-action="close">Back to ship</button>`;}
